# Generated by Django 4.1.7 on 2023-03-08 11:53

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.contrib.auth.validators.UnicodeUsernameValidator])),
                ('Mail', models.EmailField(max_length=254, unique=True)),
                ('MobileNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Standard', models.CharField(max_length=50)),
                ('SchoolName', models.TextField()),
                ('Address', models.TextField()),
                ('ParentMobileNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('MasterData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.master')),
            ],
        ),
    ]
