# Generated by Django 4.1.7 on 2023-03-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='MobileNo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ParentMobileNo',
        ),
    ]
