# Generated by Django 4.1.7 on 2023-03-08 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_master_mobileno'),
        ('student', '0002_remove_student_mobileno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Solution', models.PositiveBigIntegerField()),
                ('Description', models.TextField()),
                ('Submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Is_reviewed', models.BooleanField(default=False)),
                ('Is_correct', models.BooleanField(blank=True, null=True)),
                ('StudentData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('TaskData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.task')),
            ],
        ),
    ]
