# Generated by Django 4.1.7 on 2023-03-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_tasksubmissions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmissions',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
